"""What a tpg patch file may contain (Round 14, design decision D77).

Builds workflows/params/patch-schemas.json, which workflows/scripts/patchcheck.py
reads in the validate step of tpg-patch and tpg-create-instance (the file ships in
the tpg-scripts ConfigMap next to the scripts, so no repository clone is needed):

  values     the key tree of the tpg-instance chart values: charts/tpg-instance/values.yaml
             merged with clusters/_template/cluster.yaml and instance.yaml. A map
             whose default is empty ({}) takes any key (annotations, pgBackRest
             parameters, operator schedules); FREE_FORM lists the maps the chart
             passes through as they are (instance.resources becomes spec.resources
             of the Postgres object, which the server-side dry run checks).
  postgres   per kind a postgres patch document may target (Round 15, D81:
             Postgres, PostgresBackupLocation, PostgresBackupSchedule,
             PostgresFerretDocumentDB), the spec of its CRD: the closed JSON schema
             that tools/crd-defaults/generate.py writes from the live 4.5 CRDs
             (charts/crd-reference/schemas), without descriptions.
  operator   the operator chart values a patch may set (the user's list, Round 14):
             every other key is refused.

Called by workflows/params/generate.py (and its --check).
"""
import json
import os

import yaml

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "workflows", "params", "patch-schemas.json")
VALUE_FILES = ["charts/tpg-instance/values.yaml", "clusters/_template/cluster.yaml",
               "clusters/_template/instance.yaml"]
SCHEMA_DIR = "charts/crd-reference/schemas/sql.tanzu.vmware.com"
# the kinds the tpg-instance chart renders for an instance, and their schema files
KINDS = {"Postgres": "postgres_v1.json", "PostgresBackupLocation": "postgresbackuplocation_v1.json",
         "PostgresBackupSchedule": "postgresbackupschedule_v1.json",
         "PostgresFerretDocumentDB": "postgresferretdocumentdb_v1.json"}
# maps the chart passes through without looking at their keys
FREE_FORM = ["instance.resources"]
# keys workflows/scripts/patch-lib.sh refuses with the workflow or input that owns
# them; patchcheck.py leaves them to that message
OWNED = ["patches", "valuesOverride"]
OPERATOR = {
    "operatorImage": {"type": "image", "describe": "the operator image, <registry>/postgres-operator:<tag>; "
                      "the tag must equal the cluster's operator version (tpg-upgrade changes it)"},
    "instanceRegistryRepo": {"type": "repository", "describe": "the Postgres instance image repository, no tag"},
    "ferretDBImageRepo": {"type": "repository", "allowEmpty": True,
                          "describe": "the FerretDB image repository, no tag (empty: the default)"},
    "dockerRegistrySecretName": {"type": "k8sName", "describe": "the image pull Secret in the operator namespace"},
    "certManagerClusterIssuerName": {"type": "k8sName", "describe": "the cert-manager ClusterIssuer"},
    "certManagerNamespace": {"type": "dnsLabel", "describe": "the cert-manager namespace"},
    "resources": {"type": "resources", "describe": "limits and requests of the operator Deployment: "
                  "cpu and memory only"},
    "enableSecurityContext": {"type": "boolean", "describe": "the default security context of the operator "
                              "and its instances"},
}


def merge(dst, src):
    for k, v in (src or {}).items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            merge(dst[k], v)
        else:
            dst[k] = v
    return dst


def tree(node, path=""):
    """{"k": subtree} for a map, "*" for a map that takes any key, "list", "scalar"."""
    if isinstance(node, dict):
        if not node or path in FREE_FORM:
            return "*"
        return {k: tree(v, f"{path}.{k}" if path else k) for k, v in sorted(node.items())}
    if isinstance(node, list):
        return "list"
    return "scalar"


def strip(node):
    if isinstance(node, dict):
        return {k: strip(v) for k, v in node.items() if k != "description"}
    if isinstance(node, list):
        return [strip(v) for v in node]
    return node


def build():
    values = {}
    for f in VALUE_FILES:
        with open(os.path.join(ROOT, f)) as fh:
            merge(values, yaml.safe_load(fh))
    kinds = {}
    for kind, f in KINDS.items():
        with open(os.path.join(ROOT, SCHEMA_DIR, f)) as fh:
            kinds[kind] = strip(json.load(fh)["properties"]["spec"])
    doc = {
        "_comment": "Generated by workflows/params/generate.py (patch_schemas.py). Do not edit.",
        "values": {"tree": tree(values), "owned": OWNED},
        "postgres": {"apiVersion": "sql.tanzu.vmware.com/v1", "kinds": kinds},
        "operator": OPERATOR,
    }
    return json.dumps(doc, indent=1, sort_keys=True) + "\n"
